### ISSUE TITLE
when exercise task is finished confetti should rise.

### ISSUE THREAD

**Issue by Darkoberd00** [Schmarsch/Machine-Learning-Companion#3]
https://github.com/catdad/canvas-confetti

**Comment by Schmarsch** [comment]
![image](https://github.com/Schmarsch/Machine-Learning-Companion/assets/90196835/8e6d8fd1-5cbe-44b7-bad4-78af38f232fc)

**Comment by Darkoberd00** [comment]
ja dann halt nicht

**Comment by Darkoberd00** [comment]
ich gebe nicht auf!!!!
